# Traefik static configuration
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true

log:
  level: INFO

accessLog: {}
